import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile

buildscript {
	repositories {
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath libs.kotlin.gradlePlugin
		classpath libs.kotlin.serializationPlugin
	}
}

apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'org.jetbrains.kotlin.plugin.serialization'

apply plugin: 'application'
application {
	mainClass = 'com.jakewharton.plex.Main'
}

dependencies {
	implementation libs.clikt

	implementation libs.kotlinx.coroutines.core

	implementation libs.okhttp.core
	implementation libs.okhttp.logging

	implementation libs.kotlinx.serialization.core
	implementation libs.kotlinx.serialization.json

	testImplementation libs.junit
	testImplementation libs.jimfs
	testImplementation libs.truth
}

repositories {
	mavenCentral()
}

tasks.named("distTar").configure { task ->
	task.enabled = false
}
tasks.named("assemble").configure { task ->
	task.dependsOn(tasks.named("installDist"))
}

tasks.withType(JavaCompile).configureEach {
	sourceCompatibility = '1.8'
	targetCompatibility = '1.8'
}

tasks.withType(KotlinJvmCompile).configureEach {
	compilerOptions {
		jvmTarget = JvmTarget.JVM_1_8
		freeCompilerArgs.addAll([
			'-progressive',
		])
	}
}
