name: build

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!trunk'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: plex-orphaned-files.zip
          path: build/distributions/plex-orphaned-files.zip

  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - name: Build
        run: docker build .
