name: build

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!trunk'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: .github/workflows/.java-version
      - uses: gradle/actions/setup-gradle@v5

      - run: ./gradlew build

      - uses: actions/upload-artifact@v5
        with:
          name: plex-orphaned-files.zip
          path: build/distributions/plex-orphaned-files.zip

      - run: docker build .
